name: Docker Image CI

on:
  push:
    branches: [ "main", "develop" ]

jobs:
  test:
    runs-on: [self-hosted, linux-build-deploy-runner, Linux]  #ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
      - run: go test -v ./...

  deploy:
    needs: test
    if: github.ref == 'refs/heads/main'  # Деплоим только из main
    runs-on: [self-hosted, linux-build-deploy-runner, Linux] #linux-build-deploy-runner  #ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        run: |
          docker build -t eugenedevv2004/my-go-app:latest .
          docker push eugenedevv2004/my-go-app:latest

      - name: Run container
        run: |
          docker stop app || true
          docker rm app || true
          docker pull eugenedevv2004/my-go-app:latest
          docker run -d --name app -p 80:8888 eugenedevv2004/my-go-app:latest 